WebExam1/recipes/urls.py
from django.urls import path

from WebExam1.recipes.views import home_page, create, edit, delete, details

urlpatterns = (
    path('', home_page, name='index'),
    path('create/', create, name='create'),
    path('edit/<int:id>/', edit, name='edit'),
    path('delete/<int:id>/', delete, name='delete'),
    path('details/<int:id>/', details, name='details'),
)

WebExam1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebExam1.recipes.urls')),
]

WebExam1/recipes/models.py
from django.core import exceptions
from django.db import models


def separator_validator(value):
    if ', ' not in value:
        raise exceptions.ValidationError("The values should be separated by ', '!")
    return value


class Recipe(models.Model):
    title = models.CharField(
        max_length=30,
    )

    image_url = models.URLField()

    description = models.TextField()

    ingredients = models.CharField(
        max_length=250,
        validators=[separator_validator],
    )

    time = models.IntegerField()

WebExam1/recipes/forms.py
from django import forms

from WebExam1.recipes.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = "__all__"


# class RecipeDeleteForm(ModelForm):
#     class Meta:
#         model = Recipe
#         fields = '__all__'
#
#     def save(self, commit=True):
#         if commit:
#             self.instance.delete()
#         return self.instance

WebExam1/recipes/views.py
from django.shortcuts import render, redirect

from WebExam1.recipes.forms import RecipeForm
from WebExam1.recipes.models import Recipe


# Create your views here.
def home_page(request):
    recipes = Recipe.objects.all()

    context = {
        'recipes': recipes,
    }

    return render(request, 'index.html', context)


def create(request):
    if request.method == "GET":
        form = RecipeForm()
    else:
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            return render(request, 'create.html', {'form': form})

    context = {
        'form': form
    }

    return render(request, 'create.html', context)


def edit(request, id):
    recipe = Recipe.objects.filter(pk=id).get()
    ingredients = recipe.ingredients

    if request.method == "GET":
        form = RecipeForm(instance=recipe)
    else:
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form': form,
        'recipe': recipe,
        'ingredients': ingredients.split(", "),
    }

    return render(request, 'edit.html', context)


def delete(request, id):
    recipe = Recipe.objects.filter(pk=id).get()

    if request.method == "POST":
        recipe.delete()
        return redirect('index')

    context = {
        'recipe': recipe,
    }

    # recipe = Recipe.objects.filter(id=id).get()
    # form = RecipeDeleteForm(instance=recipe)
    # if request.method == "POST":
    #     form = RecipeDeleteForm(request.POST, instance=recipe)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('index')
    #
    # context = {
    #     'form': form,
    # }

    return render(request, 'delete.html', context)


def details(request, id):
    recipe = Recipe.objects.filter(pk=id).get()

    ingredients = recipe.ingredients

    context = {
        'recipe': recipe,
        'ingredients': ingredients.split(', '),
    }

    return render(request, 'details.html', context)

templates/create.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="post" action="{% url 'create' %}">
            {% csrf_token %}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" required="" id="id_time">#}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
</div>

    </div>


</body></html>

templates/delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action="{% url 'delete' recipe.id %}">
            {% csrf_token %}
            <label for="title">Title</label>
            <input type="text" name="title" value="{{ recipe.title }}" maxlength="30" disabled="" required="" id="id_title">
            <label for="imageURL">Image URL</label>
            <input type="url" name="image_url" value="{{ recipe.image_url }}" maxlength="200" disabled="" required="" id="id_image_url">
            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">{{ recipe.description }}</textarea>
            <label for="ingredients">Ingredients</label>
            <input type="text" name="ingredients" value="{{ recipe.ingredients }}" maxlength="250" disabled="" required="" id="id_ingredients">
            <label for="time">Time (Minutes)</label>
            <input type="number" name="time" value="{{ recipe.time }}" disabled="" required="" id="id_time">
            <input type="submit" class="button delete" value="Delete">
        </form>
    </div>
</div>

    </div>


</body></html>

templates/details.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>{{ recipe.title }}</h2>
                <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
                <div class="time">
                    <img src="/static/images/clock.png">
                    <p>{{ recipe.time }}min</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    {% for ingredient in ingredients %}
                        <li>{{ ingredient }}</li>
                    {% endfor %}
                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                    {{ recipe.description }}
                </div>
                <div class="buttons-container">
                    <a class="button edit" href="{% url 'edit' recipe.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' recipe.id %}">Delete</a>
                </div>
            </div>
        </div>

    </div>


</body></html>

templates/edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Edit Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_table }}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="{{ recipe.title }}" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="{{ recipe.image_url }}" maxlength="200"  required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10"  required="" id="id_description">{{ recipe.description }}</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="{{ recipe.ingredients }}" maxlength="250"  required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="{{ recipe.time }}" required="" id="id_time">#}
            <input type="submit" class="button edit" value="Edit">
        </form>
    </div>
</div>

    </div>


</body></html>

templates/index.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>

    <nav>
        <ul>
            <img src="/static/images/chef.png" alt="chef">
            <li class="title"><a href="/">Recipes</a></li>
            <li><a href="{% url 'create' %}">Add Recipe</a></li>
        </ul>
    </nav>
    {% for recipe in recipes %}

            <div class="items-container">
                <div class="item">
                <h2>{{ recipe.title }}</h2>
                <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
                <div class="recipe-info">
                {{ recipe.description }}
                </div>
                <div class="buttons-container">
                    <a class="button detail" href="{% url 'details' recipe.id %}">Details</a>
                    <a class="button edit" href="{% url 'edit' recipe.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' recipe.id %}">Delete</a>
                </div>
            </div>
        {% empty %}
        <h1>My Recipes</h1>
        <h2>There are no recipes.</h2>


    {% endfor %}
    </div>
{#        <div class="items-container">#}
{#            <div class="item">#}
{#                <h2>Homemade Chicken Soup</h2>#}
{#                <img class="detail-img" src="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" alt="recipe-image">#}
{#                <div class="recipe-info">#}
{#                    Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often). Take everything out of the pot. Strain the broth. Pick#}
{#                    the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.#}
{#                </div>#}
{#                <div class="buttons-container">#}
{#                    <a class="button detail" href="./details.html">Details</a>#}
{#                    <a class="button edit" href="./edit.html">Edit</a>#}
{#                    <a class="button delete" href="./delete.html">Delete</a>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="item">#}
{#                <h2>Cardamom Maple Salmon (Edit)</h2>#}
{#                <img class="detail-img" src="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1122494.jpg&amp;w=596&amp;h=596&amp;c=sc&amp;poi=face&amp;q=85" alt="recipe-image">#}
{#                <div class="recipe-info">#}
{#                    Stir salt, paprika, cardamom, coriander, and black pepper together in a bowl. Add oil and maple syrup and stir until evenly combined. Preheat a non-stick frying pan over medium-high heat, about 350 degrees F (175 degrees C). Dredge salmon pieces through#}
{#                    the maple syrup mixture until evenly coated on all sides. Cook salmon in the preheated pan until fish flakes easily with a fork, 5 to 7 minutes per side.#}
{#                </div>#}
{#                <div class="buttons-container">#}
{#                    <a class="button detail" href="./details.html">Details</a>#}
{#                    <a class="button edit" href="./edit.html">Edit</a>#}
{#                    <a class="button delete" href="./delete.html">Delete</a>#}
{#                </div>#}
{#            </div>#}

{#        </div>#}
{##}



</body>

</html>